name: test-code-quality
on: pull_request
jobs:
  install-dependencies:
    runs-on: ${{ fromJSON('["ubuntu-latest", "self-hosted"]')[github.repository == 'github/docs-internal'] }}
    strategy:
      matrix:
        node: [ 18, 20, 22 ]
    name: Test code quality
    steps:
      - uses: actions/checkout@v3
      - name: Run linting rules and tests
        uses: actions/setup-node@v3
        with:
          node-version: 22.17.0
      - run: npm ci
      - run: npm run lint:ts
      - run: npm run lint:scss
